// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $admin_auth_verify_token_ from "./routes/admin/auth/verify/[token].tsx";
import * as $admin_campaigns_id_hypotheses from "./routes/admin/campaigns/[id]/hypotheses.tsx";
import * as $admin_campaigns_id_index from "./routes/admin/campaigns/[id]/index.tsx";
import * as $admin_campaigns_id_insights from "./routes/admin/campaigns/[id]/insights.tsx";
import * as $admin_campaigns_id_interviews from "./routes/admin/campaigns/[id]/interviews.tsx";
import * as $admin_campaigns_id_map from "./routes/admin/campaigns/[id]/map.tsx";
import * as $admin_campaigns_id_participants from "./routes/admin/campaigns/[id]/participants.tsx";
import * as $admin_campaigns_index from "./routes/admin/campaigns/index.tsx";
import * as $admin_campaigns_new from "./routes/admin/campaigns/new.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $api_health from "./routes/api/health.ts";
import * as $dapi_path_ from "./routes/dapi/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $interview_token_ from "./routes/interview/[token].tsx";
import * as $AgentOrb from "./islands/AgentOrb.tsx";
import * as $InterviewRoom from "./islands/InterviewRoom.tsx";
import * as $KnowledgeMap from "./islands/KnowledgeMap.tsx";
import * as $ParticipantsTable from "./islands/ParticipantsTable.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/admin/auth/verify/[token].tsx": $admin_auth_verify_token_,
    "./routes/admin/campaigns/[id]/hypotheses.tsx":
      $admin_campaigns_id_hypotheses,
    "./routes/admin/campaigns/[id]/index.tsx": $admin_campaigns_id_index,
    "./routes/admin/campaigns/[id]/insights.tsx": $admin_campaigns_id_insights,
    "./routes/admin/campaigns/[id]/interviews.tsx":
      $admin_campaigns_id_interviews,
    "./routes/admin/campaigns/[id]/map.tsx": $admin_campaigns_id_map,
    "./routes/admin/campaigns/[id]/participants.tsx":
      $admin_campaigns_id_participants,
    "./routes/admin/campaigns/index.tsx": $admin_campaigns_index,
    "./routes/admin/campaigns/new.tsx": $admin_campaigns_new,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/api/health.ts": $api_health,
    "./routes/dapi/[...path].ts": $dapi_path_,
    "./routes/index.tsx": $index,
    "./routes/interview/[token].tsx": $interview_token_,
  },
  islands: {
    "./islands/AgentOrb.tsx": $AgentOrb,
    "./islands/InterviewRoom.tsx": $InterviewRoom,
    "./islands/KnowledgeMap.tsx": $KnowledgeMap,
    "./islands/ParticipantsTable.tsx": $ParticipantsTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
